In [2]:
RANDOM NUMBER GENERATION.

import numpy as np   # Here we can import numerical library (numpy) as np.

In [12]:
y = np.random.normal(size = (1,5))[0] #here we can assign a value to y which print any random values according to the size

In [4]:
print(y)  #Here we print the value of y

[-0.29498433 -1.05139559 -0.63777668  0.37746503  1.28829011]


In [5]:
z = np.random.randint(low = 2,high = 50,size = 4) #here we can assign a valur to the z and it gernerates some random values according to the size here.

In [6]:
print(z)  #Here print the value of z

[33 47 35 25]


In [13]:
np.random.permutation(y) #Return a new ordering of elements of z

array([-5.35996161e-01, -1.02095042e+00,  6.98832079e-04, -1.85417633e+00,
       -8.58126546e-01])

In [14]:
np.random.uniform(size=4) #Uniform distribution

array([0.55724059, 0.20127296, 0.43321858, 0.93098401])

In [11]:
np.random.normal(size = 4) #Normal distribution

array([ 0.28773073, -1.27284627,  1.28069063, -0.18822251])